# Generated by Django 4.2.11 on 2025-12-05 15:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('telegram_bot', '0005_telegramregistrationcode_assigned_to_user_email_and_more'),
        ('powerbi_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBIAlertDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para identificar esta alerta', max_length=200, verbose_name='Nombre de la alerta')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del propósito de esta alerta', verbose_name='Descripción')),
                ('group_id', models.CharField(help_text='ID del workspace de Power BI para esta alerta', max_length=100, verbose_name='Workspace/Group ID')),
                ('dataset_id', models.CharField(help_text='ID del dataset a consultar', max_length=100, verbose_name='Dataset ID')),
                ('dax_query', models.TextField(help_text="Query DAX a ejecutar. Usa EVALUATE para retornar resultados.\nEjemplo: EVALUATE TOPN(100, 'Ventas', 'Ventas'[Fecha], DESC)\n        ", verbose_name='Query DAX')),
                ('record_id_field', models.CharField(default='id', help_text='Nombre del campo en el dataset que identifica únicamente cada registro (para evitar duplicados)', max_length=100, verbose_name='Campo ID de registro')),
                ('openai_template', models.TextField(blank=True, help_text='Template específico para esta alerta.\nDeja vacío para usar el template por defecto del tenant.\nDescribe cómo quieres que OpenAI formatee los datos para Telegram.\n        ', verbose_name='Template OpenAI')),
                ('example_output', models.TextField(blank=True, help_text='Ejemplo de cómo debe verse el mensaje formateado.\nOpenAI usará este ejemplo como guía para generar mensajes similares.\n        ', verbose_name='Ejemplo de salida esperada')),
                ('check_interval_minutes', models.IntegerField(default=5, help_text='Cada cuántos minutos se ejecuta esta alerta', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Intervalo de verificación (minutos)')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='Última verificación')),
                ('default_priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Prioridad por defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Definición de Alerta',
                'verbose_name_plural': 'Definiciones de Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PowerBIAlertInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powerbi_record_id', models.CharField(help_text='Identificador único del registro en Power BI', max_length=255, verbose_name='ID de registro Power BI')),
                ('raw_data', models.JSONField(default=dict, help_text='Datos crudos del registro de Power BI', verbose_name='Datos originales')),
                ('formatted_message', models.TextField(blank=True, help_text='Mensaje formateado por OpenAI para enviar a Telegram', verbose_name='Mensaje formateado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('ignored', 'Ignorado')], default='pending', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('powerbi_created_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha en Power BI')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesado en')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instancia de Alerta',
                'verbose_name_plural': 'Instancias de Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PowerBIGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Power BI Config', max_length=100, unique=True, verbose_name='Nombre de configuración')),
                ('tenant_id', models.CharField(help_text='ID del tenant de Azure AD', max_length=100, verbose_name='Azure Tenant ID')),
                ('client_id', models.CharField(help_text='ID de la aplicación registrada en Azure AD', max_length=100, verbose_name='Client ID')),
                ('client_secret', models.CharField(help_text='Secreto de la aplicación (manejar con cuidado)', max_length=255, verbose_name='Client Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Global Power BI',
                'verbose_name_plural': 'Configuraciones Globales Power BI',
            },
        ),
        migrations.CreateModel(
            name='PowerBITenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_openai_template', models.TextField(blank=True, help_text='Template para formatear mensajes con OpenAI.\nEste template se usará para todas las alertas que no tengan uno propio.\nEjemplo: "Eres un asistente que formatea alertas de ventas para Telegram.\nGenera mensajes claros y concisos con los datos proporcionados."\n        ', verbose_name='Template OpenAI por defecto')),
                ('default_example_output', models.TextField(blank=True, help_text='Ejemplo del formato de mensaje esperado.\nOpenAI usará este ejemplo como referencia para formatear los datos.\n        ', verbose_name='Ejemplo de salida por defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Tenant Power BI',
                'verbose_name_plural': 'Configuraciones de Tenant Power BI',
            },
        ),
        migrations.AlterModelOptions(
            name='powerbialert',
            options={'ordering': ['-created_at'], 'verbose_name': '[LEGACY] Alerta Power BI', 'verbose_name_plural': '[LEGACY] Alertas Power BI'},
        ),
        migrations.AlterModelOptions(
            name='powerbiconfig',
            options={'verbose_name': '[LEGACY] Configuración de Power BI', 'verbose_name_plural': '[LEGACY] Configuraciones de Power BI'},
        ),
        migrations.RemoveIndex(
            model_name='powerbialert',
            name='powerbi_han_powerbi_idx',
        ),
        migrations.RemoveIndex(
            model_name='powerbialert',
            name='powerbi_han_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='powerbialert',
            name='powerbi_han_created_idx',
        ),
        migrations.AlterUniqueTogether(
            name='powerbialert',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='powerbiprocessinglog',
            name='config',
        ),
        migrations.AddField(
            model_name='powerbiprocessinglog',
            name='alerts_sent',
            field=models.IntegerField(default=0, verbose_name='Alertas enviadas'),
        ),
        migrations.AlterField(
            model_name='powerbialert',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_powerbi_alerts', to='company.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='powerbialert',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_alerts', to='powerbi_handler.powerbiconfig', verbose_name='Configuración'),
        ),
        migrations.AlterField(
            model_name='powerbialert',
            name='powerbi_record_id',
            field=models.CharField(max_length=255, verbose_name='ID de registro Power BI'),
        ),
        migrations.AlterField(
            model_name='powerbialert',
            name='raw_data',
            field=models.JSONField(default=dict, verbose_name='Datos originales'),
        ),
        migrations.AlterField(
            model_name='powerbiconfig',
            name='check_interval',
            field=models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(60)], verbose_name='Intervalo de verificación (segundos)'),
        ),
        migrations.AlterField(
            model_name='powerbiconfig',
            name='field_mapping',
            field=models.JSONField(default=dict, verbose_name='Mapeo de campos'),
        ),
        migrations.AddField(
            model_name='powerbitenantconfig',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='powerbi_tenant_config', to='company.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='powerbialertinstance',
            name='alert_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='powerbi_handler.powerbialertdefinition', verbose_name='Definición de alerta'),
        ),
        migrations.AddField(
            model_name='powerbialertinstance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerbi_alert_instances', to='company.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='powerbialertdefinition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerbi_alert_definitions', to='company.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='powerbialertdefinition',
            name='telegram_chats',
            field=models.ManyToManyField(blank=True, help_text='Chats de Telegram que recibirán esta alerta', related_name='powerbi_alert_definitions', to='telegram_bot.telegramchat', verbose_name='Chats destinatarios'),
        ),
        migrations.AddField(
            model_name='powerbiprocessinglog',
            name='alert_definition',
            field=models.ForeignKey(blank=True, help_text='Definición de alerta procesada (vacío para logs globales)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='powerbi_handler.powerbialertdefinition', verbose_name='Definición de alerta'),
        ),
        migrations.AddIndex(
            model_name='powerbialertinstance',
            index=models.Index(fields=['company', 'status'], name='powerbi_han_company_69ff73_idx'),
        ),
        migrations.AddIndex(
            model_name='powerbialertinstance',
            index=models.Index(fields=['powerbi_record_id'], name='powerbi_han_powerbi_7696dd_idx'),
        ),
        migrations.AddIndex(
            model_name='powerbialertinstance',
            index=models.Index(fields=['created_at'], name='powerbi_han_created_bfe132_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='powerbialertinstance',
            unique_together={('alert_definition', 'powerbi_record_id')},
        ),
        migrations.AddIndex(
            model_name='powerbialertdefinition',
            index=models.Index(fields=['company', 'is_active'], name='powerbi_han_company_99d44f_idx'),
        ),
        migrations.AddIndex(
            model_name='powerbialertdefinition',
            index=models.Index(fields=['last_check'], name='powerbi_han_last_ch_15577e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='powerbialertdefinition',
            unique_together={('company', 'name')},
        ),
    ]
