# Generated by Django 4.2.11 on 2025-12-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_handler', '0002_multi_tenant_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbiglobalconfig',
            name='default_dataset_id',
            field=models.CharField(blank=True, help_text='ID del dataset. Las alertas usarán este valor si no especifican uno propio.', max_length=100, verbose_name='Dataset ID por defecto'),
        ),
        migrations.AddField(
            model_name='powerbiglobalconfig',
            name='default_dax_query',
            field=models.TextField(blank=True, default="EVALUATE TOPN(100, 'VENTAS')", help_text='Query DAX por defecto. Las alertas usarán este valor si no especifican uno propio.', verbose_name='Query DAX por defecto'),
        ),
        migrations.AddField(
            model_name='powerbiglobalconfig',
            name='default_group_id',
            field=models.CharField(blank=True, help_text='ID del workspace de Power BI. Las alertas usarán este valor si no especifican uno propio.', max_length=100, verbose_name='Group/Workspace ID por defecto'),
        ),
        migrations.AlterField(
            model_name='powerbialertdefinition',
            name='dataset_id',
            field=models.CharField(blank=True, help_text='Deja vacío para usar el valor de la configuración global', max_length=100, verbose_name='Dataset ID'),
        ),
        migrations.AlterField(
            model_name='powerbialertdefinition',
            name='dax_query',
            field=models.TextField(blank=True, help_text='Deja vacío para usar el query por defecto de la configuración global', verbose_name='Query DAX'),
        ),
        migrations.AlterField(
            model_name='powerbialertdefinition',
            name='group_id',
            field=models.CharField(blank=True, help_text='Deja vacío para usar el valor de la configuración global', max_length=100, verbose_name='Workspace/Group ID'),
        ),
    ]
