# Generated by Django 4.2.11 on 2025-12-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi_handler', '0003_add_defaults_to_global_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerbialertdefinition',
            name='record_id_field',
        ),
    ]
