# Generated by Django 4.2.11 on 2025-09-09 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(help_text='Dirección de email del remitente', max_length=254, verbose_name='Remitente')),
                ('subject', models.CharField(help_text='Asunto del email recibido', max_length=500, verbose_name='Asunto')),
                ('body', models.TextField(help_text='Contenido completo del email', verbose_name='Cuerpo del email')),
                ('received_date', models.DateTimeField(help_text='Fecha y hora en que se recibió el email', verbose_name='Fecha de recepción')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', help_text='Prioridad asignada al email para su procesamiento', max_length=20, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('ignored', 'Ignorado')], default='pending', help_text='Estado actual del procesamiento del email', max_length=20, verbose_name='Estado')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se procesó el email', null=True, verbose_name='Procesado el')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se envió la alerta por Telegram', null=True, verbose_name='Enviado el')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error en caso de fallo en el procesamiento', verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Usuario al que se ha asignado esta alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emails', to='user.user', verbose_name='Asignado a')),
                ('company', models.ForeignKey(help_text='Empresa a la que corresponde este email', on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Email Recibido',
                'verbose_name_plural': 'Emails Recibidos',
                'ordering': ['-received_date'],
                'indexes': [models.Index(fields=['company', 'status'], name='emails_rece_company_b1d8b8_idx'), models.Index(fields=['received_date'], name='emails_rece_receive_aac5e5_idx'), models.Index(fields=['status'], name='emails_rece_status_a82ed6_idx'), models.Index(fields=['priority'], name='emails_rece_priorit_1d63b3_idx')],
            },
        ),
    ]
