# Generated by Django 4.2.11 on 2025-09-09 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='receivedemail',
            name='emails_rece_company_b1d8b8_idx',
        ),
        migrations.RemoveField(
            model_name='receivedemail',
            name='company',
        ),
    ]
