"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Cargar variables de entorno desde el archivo .env
load_dotenv(os.path.join(Path(__file__).resolve().parent.parent.parent, ".env"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-yl8w&bw1$3izhp7sb4sx%l&e!u)y)f1cj%itag2klnc$^n54_x"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [
      "discoveragents.online",
      "www.discoveragents.online",
      "localhost",
      "127.0.0.1",
]

  # Add after ALLOWED_HOSTS:
CSRF_TRUSTED_ORIGINS = [
      "https://discoveragents.online",
      "https://www.discoveragents.online",
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



# Application definition

# Apps compartidas (esquema público)
SHARED_APPS = [
    "django_tenants",  # Debe ir PRIMERO
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Apps del tenant
    "company",  # Contiene el modelo tenant
    "telegram_bot",  # Bot centralizado para todas las empresas
    "powerbi_handler",  # Integración con Power BI
]

# Apps específicas del tenant (esquema privado)
TENANT_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Apps de negocio
    "user",
]

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",  # DEBE ir PRIMERO
    "company.middleware.TenantAdminMiddleware",  # Configurar admin según esquema
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "company.context_processors.schema_context",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": os.getenv("POSTGRES_DB", "distribuidora_lucas"),
        "USER": os.getenv("POSTGRES_USER", "postgres"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "postgres"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ==================================
# CONFIGURACIÓN POWER BI
# ==================================
# NOTA: Las credenciales de Power BI ahora se configuran en el admin
# a través del modelo PowerBIGlobalConfig. Estas variables se mantienen
# solo para compatibilidad/migración inicial.
POWERBI_TENANT_ID = os.getenv("POWERBI_TENANT_ID", "")
POWERBI_CLIENT_ID = os.getenv("POWERBI_CLIENT_ID", "")
POWERBI_CLIENT_SECRET = os.getenv("POWERBI_CLIENT_SECRET", "")
POWERBI_GROUP_ID = os.getenv("POWERBI_GROUP_ID", "")
POWERBI_DATASET_ID = os.getenv("POWERBI_DATASET_ID", "")
POWERBI_CHECK_INTERVAL = int(os.getenv("POWERBI_CHECK_INTERVAL", 60))

# ==================================
# CONFIGURACIÓN OPENAI
# ==================================
# API Key de OpenAI para formatear mensajes de alertas
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
# Modelo a usar (gpt-3.5-turbo es más económico, gpt-4 más preciso)
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-3.5-turbo")
# Tokens máximos para la respuesta
OPENAI_MAX_TOKENS = int(os.getenv("OPENAI_MAX_TOKENS", 500))

# ==================================
# CONFIGURACIÓN CELERY & REDIS
# ==================================
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULE = {
    # Task maestro que procesa todas las alertas de Power BI
    # Se ejecuta cada 60 segundos, pero cada alerta tiene su propio intervalo
    "process-all-powerbi-alerts": {
        "task": "powerbi_handler.tasks.process_all_powerbi_alerts",
        "schedule": POWERBI_CHECK_INTERVAL,  # 60 segundos por defecto
    },
}

# ==================================
# CONFIGURACIÓN DE ALERTAS
# ==================================
HIGH_PRIORITY_KEYWORDS = [
    kw.strip()
    for kw in os.getenv(
        "HIGH_PRIORITY_KEYWORDS", "venta,urgente,importante,alerta,crítico,error"
    ).split(",")
]
MEDIUM_PRIORITY_KEYWORDS = [
    kw.strip()
    for kw in os.getenv(
        "MEDIUM_PRIORITY_KEYWORDS", "pedido,orden,consulta,información"
    ).split(",")
]
LOW_PRIORITY_KEYWORDS = [
    kw.strip()
    for kw in os.getenv(
        "LOW_PRIORITY_KEYWORDS", "newsletter,promoción,marketing,notificación"
    ).split(",")
]

# ==================================
# CONFIGURACIÓN TELEGRAM
# ==================================
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_WEBHOOK_URL = os.getenv("TELEGRAM_WEBHOOK_URL", "")
TELEGRAM_WEBHOOK_SECRET = os.getenv("TELEGRAM_WEBHOOK_SECRET", "")

# Chat ID por defecto para alertas (se puede configurar desde el admin)
TELEGRAM_DEFAULT_CHAT_ID = os.getenv("TELEGRAM_DEFAULT_CHAT_ID", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "app.log",
            "formatter": "verbose",
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "powerbi_handler": {
            "handlers": ["file", "console"],
            "level": os.getenv("LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

# Crear directorio de logs si no existe
os.makedirs(BASE_DIR / "logs", exist_ok=True)

# ==================================
# CONFIGURACIÓN DJANGO TENANTS
# ==================================

# Modelo de tenant
TENANT_MODEL = "company.Company"

# Modelo de dominio
TENANT_DOMAIN_MODEL = "company.Domain"

# Configuración de la base de datos para tenants
DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)

# Configuración del esquema público
PUBLIC_SCHEMA_NAME = "public"
PUBLIC_SCHEMA_URLCONF = "app.urls_public"
