# Generated by Django 5.2.5 on 2025-09-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramconfig',
            name='webhook_secret_token',
        ),
        migrations.RemoveField(
            model_name='telegramconfig',
            name='webhook_url',
        ),
    ]
