# Generated by Django 4.2.11 on 2025-10-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este chat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_chats', to='company.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este mensaje', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_messages', to='company.company', verbose_name='Empresa'),
        ),
    ]
