# Generated by Django 4.2.11 on 2025-10-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_telegramchat_company_telegrammessage_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='bot',
            field=models.ForeignKey(blank=True, help_text='Bot que enviará mensajes a este chat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='telegram_bot.telegramconfig', verbose_name='Bot de Telegram'),
        ),
    ]
