# Generated by Django 4.2.11 on 2025-10-20 02:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0003_telegramchat_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramRegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único de registro (generado automáticamente)', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener 8 caracteres alfanuméricos en mayúsculas', regex='^[A-Z0-9]{8}$')], verbose_name='Código')),
                ('expires_at', models.DateTimeField(help_text='Fecha y hora de expiración del código', verbose_name='Expira en')),
                ('is_used', models.BooleanField(default=False, help_text='Indica si el código ya fue utilizado', verbose_name='Usado')),
                ('used_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se usó el código', null=True, verbose_name='Usado en')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre este código (opcional)', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Empresa a la que se asignará el chat cuando se use este código', on_delete=django.db.models.deletion.CASCADE, related_name='registration_codes', to='company.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que generó este código', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registration_codes', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('used_by_chat', models.ForeignKey(blank=True, help_text='Chat que utilizó este código para registrarse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_code_used', to='telegram_bot.telegramchat', verbose_name='Usado por chat')),
            ],
            options={
                'verbose_name': 'Código de Registro',
                'verbose_name_plural': 'Códigos de Registro',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='telegram_bo_code_d8cc06_idx'), models.Index(fields=['company', 'is_used'], name='telegram_bo_company_9fb7ec_idx')],
            },
        ),
    ]
