# Generated by Django 4.2.11 on 2025-10-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_telegramregistrationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramregistrationcode',
            name='assigned_to_user_email',
            field=models.EmailField(blank=True, help_text='Email del usuario de la empresa al que se le asignó este código', max_length=254, null=True, verbose_name='Email del usuario asignado'),
        ),
        migrations.AddField(
            model_name='telegramregistrationcode',
            name='assigned_to_user_name',
            field=models.CharField(blank=True, help_text='Nombre del usuario de la empresa al que se le asignó este código', max_length=150, null=True, verbose_name='Nombre del usuario asignado'),
        ),
    ]
