# Generated by Django 4.2.11 on 2025-09-09 02:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMAPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para esta configuración IMAP', max_length=100, unique=True, verbose_name='Nombre de configuración')),
                ('host', models.CharField(help_text='Dirección del servidor IMAP (ej: imap.gmail.com)', max_length=255, verbose_name='Servidor IMAP')),
                ('port', models.IntegerField(default=993, help_text='Puerto del servidor IMAP (993 para SSL, 143 para no SSL)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Puerto')),
                ('username', models.CharField(help_text='Dirección de email o nombre de usuario', max_length=255, verbose_name='Usuario/Email')),
                ('password', models.CharField(help_text='Contraseña o app password', max_length=255, verbose_name='Contraseña')),
                ('use_ssl', models.BooleanField(default=True, help_text='Usar conexión segura SSL/TLS', verbose_name='Usar SSL')),
                ('inbox_folder', models.CharField(default='INBOX', help_text='Nombre de la carpeta de entrada', max_length=100, verbose_name='Carpeta de entrada')),
                ('processed_folder', models.CharField(blank=True, default='Processed', help_text='Carpeta donde mover emails procesados (opcional)', max_length=100, verbose_name='Carpeta procesados')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta configuración está activa', verbose_name='Activa')),
                ('check_interval', models.IntegerField(default=300, help_text='Cada cuántos segundos verificar nuevos emails', validators=[django.core.validators.MinValueValidator(60)], verbose_name='Intervalo de verificación (segundos)')),
                ('max_emails_per_check', models.IntegerField(default=50, help_text='Número máximo de emails a procesar por verificación', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Máx. emails por verificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('last_check', models.DateTimeField(blank=True, help_text='Última vez que se verificaron emails en esta cuenta', null=True, verbose_name='Última verificación')),
                ('company', models.ForeignKey(help_text='Empresa asociada a esta configuración', on_delete=django.db.models.deletion.CASCADE, related_name='imap_configs', to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración IMAP',
                'verbose_name_plural': 'Configuraciones IMAP',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IMAPProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Éxito'), ('error', 'Error'), ('warning', 'Advertencia'), ('info', 'Información')], max_length=20, verbose_name='Estado')),
                ('message', models.TextField(help_text='Mensaje de log detallado', verbose_name='Mensaje')),
                ('emails_processed', models.IntegerField(default=0, help_text='Número de emails procesados en esta ejecución', verbose_name='Emails procesados')),
                ('emails_failed', models.IntegerField(default=0, help_text='Número de emails que fallaron al procesar', verbose_name='Emails fallidos')),
                ('processing_time', models.FloatField(blank=True, help_text='Tiempo que tomó el procesamiento', null=True, verbose_name='Tiempo de procesamiento (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('imap_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='imap_handler.imapconfiguration', verbose_name='Configuración IMAP')),
            ],
            options={
                'verbose_name': 'Log de procesamiento IMAP',
                'verbose_name_plural': 'Logs de procesamiento IMAP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailProcessingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para esta regla', max_length=100, verbose_name='Nombre de la regla')),
                ('criteria_type', models.CharField(choices=[('subject_contains', 'Asunto contiene'), ('sender_contains', 'Remitente contiene'), ('body_contains', 'Cuerpo contiene'), ('subject_regex', 'Asunto coincide con regex'), ('sender_regex', 'Remitente coincide con regex')], help_text='Tipo de criterio para evaluar el email', max_length=20, verbose_name='Tipo de criterio')),
                ('criteria_value', models.CharField(help_text='Valor o patrón a buscar según el tipo de criterio', max_length=500, verbose_name='Valor del criterio')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], help_text='Prioridad que se asignará si se cumple el criterio', max_length=20, verbose_name='Prioridad a asignar')),
                ('assign_to_role', models.CharField(blank=True, choices=[('manager', 'Manager'), ('supervisor', 'Supervisor')], help_text='Rol al que asignar automáticamente (opcional)', max_length=20, null=True, verbose_name='Asignar a rol')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta regla está activa', verbose_name='Activa')),
                ('order', models.IntegerField(default=0, help_text='Orden de evaluación de las reglas (menor número = mayor prioridad)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('imap_config', models.ForeignKey(help_text='Configuración IMAP a la que aplica esta regla', on_delete=django.db.models.deletion.CASCADE, related_name='processing_rules', to='imap_handler.imapconfiguration', verbose_name='Configuración IMAP')),
            ],
            options={
                'verbose_name': 'Regla de procesamiento',
                'verbose_name_plural': 'Reglas de procesamiento',
                'ordering': ['imap_config', 'order', 'name'],
            },
        ),
    ]
