# Generated by Django 4.2.11 on 2025-09-09 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imap_handler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imapconfiguration',
            name='company',
        ),
    ]
