# Generated by Django 5.2.5 on 2025-09-02 23:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('manager', 'Manager'), ('supervisor', 'Supervisor'), ('client', 'Cliente')], help_text='Define el tipo de rol en el sistema', max_length=20, unique=True, verbose_name='Tipo de rol')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del rol y sus responsabilidades', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo del usuario', max_length=150, verbose_name='Nombre completo')),
                ('email', models.EmailField(help_text='Correo electrónico del usuario', max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, help_text='Número de teléfono con código de país', max_length=17, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='ID del chat de Telegram para envío de alertas', max_length=50, verbose_name='Chat ID de Telegram')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el usuario está activo en el sistema', verbose_name='Activo')),
                ('can_receive_alerts', models.BooleanField(default=True, help_text='Indica si el usuario puede recibir notificaciones de alertas', verbose_name='Puede recibir alertas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(help_text='Empresa a la que pertenece el usuario', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='company.company', verbose_name='Empresa')),
                ('role', models.ForeignKey(help_text='Rol del usuario en el sistema', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='user.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['name'],
                'unique_together': {('email', 'company')},
            },
        ),
    ]
